layout_spectrum: 0.1303258
typography_spectrum: 0.1380606
color:
  saturation: 0.2180451
  lightness: 0.7775689
  brandStrength: 0.6177945
  brandColors:
    - '#FCFBFF'
    - '#30392F'
    - '#656542'
    - '#657689'
    - '#909A66'
  rhythmicContrast: 0.2938597
name: Kitakitssapanay
