typography_spectrum: 0.1380606
color:
  brandColors:
    - '#FCFBFF'
    - '#30392F'
    - '#656542'
    - '#657689'
    - '#909A66'
  brandStrength: 0.5
  lightness: 0.7775689
  saturation: 0.2180451
  rhythmicContrast: 0.2938597
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26581
analytics:
  google: null
  facebook: null
  twitter: null
name: Kitakitssapanay
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: af9310f2-771e-4649-b2e4-644363fb94f5
    name: Artificial reef
    type: content
  - id: a747ad5f-1f74-4db2-a106-ec729a92d0c7
    name: Laatste week Antique
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Blog of Marielle en Gertjan
purpose: []
