collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1380606
color:
  saturation: 0.2180451
  brandStrength: 0.6177945
  rhythmicContrast: 0.2938597
  brandColors:
    - '#FCFBFF'
    - '#30392F'
    - '#656542'
    - '#657689'
    - '#909A66'
  lightness: 0.7775689
layout_spectrum: 0
name: Kitakitssapanay
